config/routes.rb
Rails.application.routes.draw do
  # Block route for devise registration controller
  devise_for :users
  root 'pages#home'
  resources :user, :controller => "user" do
    collection { post :import }
  end
  resources :courses
  resources :topics
  resources :instructors
  resources :categories
  resources :subscriptions, only: [:new, :create, :edit, :update]
  get 'mark_as_done' => 'topic_completition#mark_as_done'
  get 'course_information' => 'pages#course_information'
  get 'plans_information' => 'pages#plans_information'
  get 'politicas_servicio' => 'pages#politicas_servicio'
  get 'faq' => 'pages#faq'
  get 'my_courses' => 'courses#my_courses'
  get 'welcome_new_user' => 'pages#welcome_video_user'
  get 'welcome_new_subscriptor' => 'pages#welcome_video_subscriptor'
  get 'discourse/sso' => 'discourse_sso#sso'
  get 'search_by_category' => 'pages#search_by_category'
end

app/models/instructor.rb
# == Schema Information
#
# Table name: instructors
#
#  id                 :integer          not null, primary key
#  name               :string
#  background         :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  twitter_username   :string
#

class Instructor < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	has_and_belongs_to_many :courses
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	before_action :authenticate_user!
	before_filter :content_permission

	def index
		@instructors = Instructor.all
	end

	def new	
		@instructor = Instructor.new
	end

	def create
		@instructor = Instructor.new(instructor_params)
		if @instructor.save
  	  flash[:notice] = "El instructor #{@instructor.name} fue creado con exito"
  	  redirect_to instructors_path
  	else
  		flash[:alert] = "Ha ocurrido un error y el instructor #{@instructor.name}, no ha sido almacenado"
    	render :action => 'new'
  	end
	end

	def edit
		@instructor = Instructor.find(params[:id])
	end

	def update
		@instructor = Instructor.find(params[:id])
		if @instructor.update(instructor_params)
			redirect_to instructors_path
		else
			flash[:alert] = 'Se ha encontrado un error al intentar editar este instructor'
			render 'edit'
		end
	end

	def destroy
		@instructor = Instructor.find(params[:id])
		@instructor.destroy
		redirect_to instructors_path
	end

	private
		def instructor_params
  		params.require(:instructor).permit(:name, :background, :image, :twitter_username)
		end
		
		def content_permission
	    unless current_user.admin? || current_user.content_manager?
	      redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos de administrador para acceder a esta ruta."
	    end
  	end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor, :html => { :id => "instructorForm"}) do |instructor| %>
	<h3 class="right-line text-left">NUEVO INSTRUCTOR</h3>
	<div class="row">
		<div class="col-md-12 text-left">
			<div class="field form-group">
				<%= instructor.label :name, "Nombre del Instructor:", class: "lead lead-lg" %>
				<%= instructor.text_field :name, required: true, class: "form-control" %>
			</div>

			<div class="field form-group">
				<%= instructor.label :background, "Background:", class: "lead lead-lg" %>
				<%= instructor.text_area :background, class: "form-control" %>
			</div>

			<div class="field form-group">
				<%= instructor.label :twitter_username, "Usuario de twitter (sin @):", class: "lead lead-lg" %>
				<%= instructor.text_field :twitter_username, class: "form-control" %>
			</div>

			<div class="field form-group">
			  <%= instructor.label :image, "Imagen del instructor:", class: "lead lead-lg" %>
			  <%= instructor.file_field :image, class: "form-control" %>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="actions form-group text-center">		  	
		  			<%= instructor.submit "Guardar Instructor", class: "btn btn-ar btn-lg btn-success" %>
		  		</div>
				</div>	
			</div>
		</div>
	</div>
<% end %>

app/views/instructors/edit.html.erb
<div class="container">
	<div class="row">
		<h2 class="right-line">EDITAR UN INSTRUCTOR</h2>
	</div>
	<%= render 'form' %>		
</div>

app/views/instructors/index.html.erb
<div class="container">
  <section class="margin-bottom">
    <div class="row">
      <div class="col-md-12">
        <h2 class="right-line">LISTADO DE INSTRUCTORES REGISTRADOS</h2>
      </div>			
			<% @instructors.each do |instructor| %>
				<div class="col-sm-6 col-md-3">
				  <div class="thumbnail">
				    <img src="<%= instructor.image.url(:medium) %>" alt="..." class="thumbnail_custom_image">
				    <div class="caption">
				      <h3><%= instructor.name %></h3>
				      <p><%= instructor.background %></p>
				      <p><%= link_to "Editar", edit_instructor_path(instructor), class: "btn btn-ar btn-warning" %> <%= link_to instructor_path(instructor), method: :delete, data: { confirm: '¿Esta seguro que desea elminar esta usuario?' }, class: "btn btn-ar btn-danger" do %><span>Eliminar</span><% end %>
				    </div>
				  </div>
				</div>
			<% end %>
    </div> <!-- row -->
    <div class="row">
			<div class="col-md-6 text-center col-md-offset-3" id="btn-new-user">
				<%= link_to "Crear Un Nuevo Instructor", new_instructor_path, class: "btn btn-lg btn-ar btn-success" %>
			</div>
		</div>
  </section>
</div>

app/views/instructors/new.html.erb
<div class="container">
	<div class="row">
		<h2 class="right-line">ALMACENAR UN NUEVO INSTRUCTOR</h2>
	</div>
	<%= render 'form' %>		
</div>