config/routes.rb
Rails.application.routes.draw do
  # Block route for devise registration controller
  devise_for :users
  root 'pages#home'
  resources :user, :controller => "user" do
    collection { post :import }
  end
  resources :courses
  resources :topics
  resources :instructors
  resources :categories
  resources :subscriptions, only: [:new, :create, :edit, :update]
  get 'mark_as_done' => 'topic_completition#mark_as_done'
  get 'course_information' => 'pages#course_information'
  get 'plans_information' => 'pages#plans_information'
  get 'politicas_servicio' => 'pages#politicas_servicio'
  get 'faq' => 'pages#faq'
  get 'my_courses' => 'courses#my_courses'
  get 'welcome_new_user' => 'pages#welcome_video_user'
  get 'welcome_new_subscriptor' => 'pages#welcome_video_subscriptor'
  get 'discourse/sso' => 'discourse_sso#sso'
  get 'search_by_category' => 'pages#search_by_category'
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id                 :integer          not null, primary key
#  title              :string
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  course_type        :integer
#  new_course         :boolean
#  new_course_days    :integer
#

class Course < ActiveRecord::Base
	enum course_type: [:free, :with_charge]
	has_attached_file :image, :styles => { :medium => "300x200#", :thumb => "100x100#" }, convert_options: { medium: " -gravity center -crop '300x300+0+0'" , thumbnail: "-gravity Center -crop 500x500+0+0 +repage -resize 100x100^" }

  # has_attached_file :image, styles: { medium: "300x300>" , thumbnail: '100x100^' }, convert_options: { medium: " -gravity center -crop '300x300+0+0'" , thumbnail: "-gravity Center -crop 500x500+0+0 +repage -resize 100x100^" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	has_many :enrollments
  has_many :users, through: :enrollments
  has_many :lessons, dependent: :destroy
	has_and_belongs_to_many :instructors
	has_and_belongs_to_many :categories
	accepts_nested_attributes_for :lessons, :reject_if => :all_blank, allow_destroy: true
  validates_associated :lessons

  def self.has_new_course_days?
    @courses = Course.where(new_course: true)
    puts "Hay #{@courses.count} cursos marcados como nuevos"    
    @courses.each do |course|
      course.update(:new_course_days => course.new_course_days-=1)
      if course.new_course_days == 0
        course.update(:new_course => false)
      end
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user!
	before_filter :content_permission, :only => [:show]
	before_filter :has_permission?, :only => [:new,:create,:edit,:update]

	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
		lessons = @course.lessons.build
 		topics = lessons.topics.build
 		resources = topics.resources.build
	end

	def create
		@course = Course.new(course_params)
		@course.instructor_ids = params[:course][:instructor_ids]
		@course.category_ids = params[:course][:category_ids]
		if @course.save
  	  flash[:notice] = "El course #{@course.title} fue creado con exito"
  	  redirect_to courses_path
  	else
  		flash[:alert] = "Ha ocurrido un error y la guía #{@course.title}, no ha sido almacenada"
    	render :action => 'new'
  	end
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		if @course.update(course_params)
			redirect_to courses_path
		else
			flash[:alert] = 'Se ha encontrado un error al intentar editar esta guía'
			render 'edit'
		end
	end

	def show
		@topics_ready_ids = current_user.topics.pluck(:id)
		@course = Course.find(params[:id])
		@instructors = @course.instructors
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		redirect_to courses_path
	end

	def my_courses
		@courses = current_user.courses
	end

	private
		def course_params
  		params.require(:course).permit(:title, :description, :new_course, :new_course_days, :image, :course_type, { :instructor_ids => [] }, { :category_ids => [] }, lessons_attributes: [:id,:title,:description,:_destroy, topics_attributes: [:id,:title,:description,:content_url, :activities, :document, :transcription, :_destroy, resources_attributes: [ :id, :title, :description, :link_url, :_destroy]]])
		end

		def content_permission
	    if Course.find(params[:id]).with_charge?
	    	unless current_user.vip_user? || current_user.admin? || current_user.content_manager? || current_user.guest?
	    		redirect_to root_path, :alert => "Lo sentimos, usted no posee una cuenta VIP, por lo tanto no puede acceder a la información de la guía: #{Course.find(params[:id]).title}."
	    	end
	    end
  	end

  	def has_permission?
  		unless current_user.admin? || current_user.content_manager?
  			redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos para acceder a esta ruta"
  		end
  	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courses_instructor_form.html.erb
<fieldset class="form-group register">
	<h3 class="right-line text-left">NUEVO INSTRUCTOR</h3>
	<div class="row">
		<div class="col-md-12 text-left">

			<div class="field form-group">
				<%= courses_instructor.label :name, "Nombre del Instructor:", class: "lead lead-lg" %>
				<%= courses_instructor.collection_select :instructor_id, Instructor.all, :id, :name, {prompt: 'Seleccione un instructor'}, class: "type-register", required: true %>
			</div>

			<div class="form-group">
				<%= courses_instructor.hidden_field :_destroy %>
				<%= link_to "Borrar Instructor", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
			</div>
		</div>	
	</div>
</fieldset>

app/views/courses/_lesson_form.html.erb
<fieldset class="form-group register">
	<h3 class="right-line text-left">NUEVO LESSON</h3>
	<div class="row">
		<div class="col-md-12 text-left">
			<div class="field form-group">
				<%= lesson.label :title, "Título", class: "lead lead-lg" %>
				<%= lesson.text_field :title, required: true, class: "form-control" %>
			</div>
			<div class="field form-group">
				<%= lesson.label :description, "Descripción", class: "lead lead-lg" %>
				<%= lesson.text_area :description, class: "form-control" %>
			</div>
			<div class="form-group">					
				<%= lesson.hidden_field :_destroy %>
				<%= link_to "Borrar Lesson", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
			</div>
		</div>
	</div>
		
	<%= lesson.fields_for :topics do |topic| %>					
		<fieldset class="form-group register">
			<h3 class="right-line text-left">NUEVO TOPIC</h3>
			<div class="row">
				<div class="col-md-10 col-md-offset-2 text-left">
					<div class="field form-group">
						<%= topic.label :title, "Título:", class: "lead lead-lg" %>
						<%= topic.text_field :title, required: true, class: "form-control" %>
					</div>

					<div class="field form-group">
						<%= topic.label :description, "Descripción:", class: "lead lead-lg" %>
						<%= topic.text_area :description, required: true,class: "form-control" %>
					</div>
					
					<!-- Conditional to add Video or PDF file for topic -->
					<div class="field form-group">						
						<h4>Contenido de apoyo para la guía, escoja si lleva Archivo PDF o Video Clip</h4>
						<select class="form-control content_select">
							<option disabled selected> Seleccione una opción </option>
						  <option value="pdf">Archivo PDF</option>
						  <option value="video">Video Clip desde Vimeo</option>						  
						</select>

						<div class="field form-group  pdf_field" style='display: none'>
						  <%= topic.label :document, "PDF de la guía:", class: "lead lead-lg" %>
						  <%= topic.file_field :document, class: "form-control file_input" %>
						</div>

						<div class="field form-group  video_field" style='display: none'>
							<%= topic.label :content_url, "URL Video:", class: "lead lead-lg" %>
							<%= topic.text_field :content_url, class: "form-control video_url" %>
						</div>
					</div>

					<div class="field form-group">
						<%= topic.label :activities, "Acciones para aplicar en proyecto:", class: "lead lead-lg" %>
						<p>Para almacenar las diferentes acciones que corresponden a este topic se debe hacer uso del siguiente formato, este contiene una lista no ordenada con tags de HTML donde cada item debe ir entre tagas li, como se muestra a continuación:<br>
							&nbsp&nbsp&nbsp &ltul class="list-group"&gt<br>
								&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &ltli class="list-group-item"&gtNombre de la acción&lt/li&gt<br>
							&nbsp&nbsp&nbsp &lt/ul&gt					
						</p>
						<%= topic.text_area :activities, required: true,:rows => 5, class: "form-control" %>
					</div>

					<div class="field form-group">
						<%= topic.label :transcription, "Videotexto(Transcription):", class: "lead lead-lg" %>
						<p>Para almacenar el texto en diferentes parrafos, debe hacer uso del siguiente formato, este contiene cada parrafo entre tags de HTML tipo p, como se muestra a continuación:<br><br>
							&ltp&gtLorem ipsum dolor sit amet, quo illud eleifend ne. Vel ei zril laudem quaestio, eu alia modus scriptorem vix. Qui ex pericula assentior, utamur ornatus patrioque an pro, ne equidem facilis phaedrum sea. Modo nullam nominati cu nam, cum ut choro quando nominavi. Has illud tation consulatu et. Cu antiopam tractatos ius, et hinc paulo vis.&lt/p&gt<br>
						</p>
						<%= topic.text_area :transcription, rows: 10, required: true,class: "form-control" %>
					</div>

					<div class="form-group">
						<%= topic.hidden_field :_destroy %>
						<%= link_to "Borrar Topic", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
					</div>
				</div>
			</div>
			
			<%= topic.fields_for :resources do |resource| %>	
				<fieldset class="form-group register">
					<h3 class="right-line text-left">NUEVO RECURSO</h3>
					<div class="col-md-8 col-md-offset-4 text-left">
						<div class="field form-group">
							<%= resource.label :title, "Título:", class: "lead lead-lg" %>
							<%= resource.text_field :title, required: true, class: "form-control" %>
						</div>

						<div class="field form-group">
							<%= resource.label :description, "Descripción:", class: "lead lead-lg" %>
							<%= resource.text_area :description, required: true,class: "form-control" %>
						</div>

						<div class="field form-group">
							<%= resource.label :link_url, "URL del recurso:", class: "lead lead-lg" %>
							<%= resource.text_field :link_url, required: true, class: "form-control" %>
						</div>

						<div class="form-group">
							<%= resource.hidden_field :_destroy %>
							<%= link_to "Borrar Recurso", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
						</div>
					</div>
				</fieldset>
			<% end %>

			<div class="row">
				<div class="col-md-12">
				  <div class="actions form-group text-center">
				  	<%= link_to_add_resources "Click aqui para agregar un recurso", topic, :resources %>
				  </div>
			  </div>
			</div>
		</fieldset>									
	<% end %>

	<div class="row">
		<div class="col-md-12">
		  <div class="actions form-group text-left">
		  	<%= link_to_add_topics "Agregar topic", lesson, :topics %>
		  </div>
	  </div>
	</div>
</fieldset>

app/views/courses/_lesson_form_edit.html.erb
<fieldset class="form-group register">
	<h3 class="right-line text-left">LESSON</h3>
	<div class="row">
		<div class="col-md-12 text-left">
			<div class="field form-group">
				<%= lesson.label :title, "Título", class: "lead lead-lg" %>
				<%= lesson.text_field :title, required: true, class: "form-control" %>
			</div>
			<div class="field form-group">
				<%= lesson.label :description, "Descripción", class: "lead lead-lg" %>
				<%= lesson.text_area :description, class: "form-control" %>
			</div>
			<div class="form-group">					
				<%= lesson.hidden_field :_destroy %>
				<%= link_to "Borrar Lesson", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
			</div>
		</div>
	</div>
		
	<%= lesson.fields_for :topics do |topic| %>					
		<fieldset class="form-group register">
			<h3 class="right-line text-left">TOPIC</h3>
			<div class="row">
				<div class="col-md-10 col-md-offset-2 text-left">
					<div class="field form-group">
						<%= topic.label :title, "Título:", class: "lead lead-lg" %>
						<%= topic.text_field :title, required: true, class: "form-control" %>
					</div>
					
					<div class="field form-group">
						<%= topic.label :description, "Descripción:", class: "lead lead-lg" %>
						<%= topic.text_area :description, required: true,class: "form-control" %>
					</div>
										
					<div class="field form-group">																		
						<div class="field form-group  pdf_field">
						  <%= topic.label :document, "PDF de la guía:", class: "lead lead-lg" %>
						  <%= topic.file_field :document, class: "form-control file_input" %>
						</div>

						<div class="field form-group  video_field">
							<%= topic.label :content_url, "URL Video:", class: "lead lead-lg" %>
							<%= topic.text_field :content_url, class: "form-control video_url" %>
						</div>
					</div>

					<div class="field form-group">
						<%= topic.label :activities, "Acciones para aplicar en proyecto:", class: "lead lead-lg" %>
						<p>Para almacenar las diferentes acciones que corresponden a este topic se debe hacer uso del siguiente formato, este contiene una lista no ordenada con tags de HTML donde cada item debe ir entre tagas li, como se muestra a continuación:<br>
							&nbsp&nbsp&nbsp &ltul class="list-group"&gt<br>
								&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &ltli class="list-group-item"&gtNombre de la acción&lt/li&gt<br>
							&nbsp&nbsp&nbsp &lt/ul&gt					
						</p>
						<%= topic.text_area :activities, required: true,:rows => 5, class: "form-control" %>
					</div>

					<div class="field form-group">
						<%= topic.label :transcription, "Videotexto(Transcription):", class: "lead lead-lg" %>
						<p>Para almacenar el texto en diferentes parrafos, debe hacer uso del siguiente formato, este contiene cada parrafo entre tags de HTML tipo p, como se muestra a continuación:<br><br>
							&ltp&gtLorem ipsum dolor sit amet, quo illud eleifend ne. Vel ei zril laudem quaestio, eu alia modus scriptorem vix. Qui ex pericula assentior, utamur ornatus patrioque an pro, ne equidem facilis phaedrum sea. Modo nullam nominati cu nam, cum ut choro quando nominavi. Has illud tation consulatu et. Cu antiopam tractatos ius, et hinc paulo vis.&lt/p&gt<br>
						</p>
						<%= topic.text_area :transcription, rows: 10, required: true,class: "form-control" %>
					</div>

					<div class="form-group">
						<%= topic.hidden_field :_destroy %>
						<%= link_to "Borrar Topic", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
					</div>
				</div>
			</div>
			
			<%= topic.fields_for :resources do |resource| %>	
				<fieldset class="form-group register">
					<h3 class="right-line text-left">NUEVO RECURSO</h3>
					<div class="col-md-8 col-md-offset-4 text-left">
						<div class="field form-group">
							<%= resource.label :title, "Título:", class: "lead lead-lg" %>
							<%= resource.text_field :title, required: true, class: "form-control" %>
						</div>

						<div class="field form-group">
							<%= resource.label :description, "Descripción:", class: "lead lead-lg" %>
							<%= resource.text_area :description, required: true,class: "form-control" %>
						</div>

						<div class="field form-group">
							<%= resource.label :link_url, "URL del recurso:", class: "lead lead-lg" %>
							<%= resource.text_field :link_url, required: true, class: "form-control" %>
						</div>

						<div class="form-group">
							<%= resource.hidden_field :_destroy %>
							<%= link_to "Borrar Recurso", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
						</div>
					</div>
				</fieldset>
			<% end %>

			<div class="row">
				<div class="col-md-12">
				  <div class="actions form-group text-center">
				  	<%= link_to_add_resources "Click aqui para agregar un recurso", topic, :resources %>
				  </div>
			  </div>
			</div>
		</fieldset>									
	<% end %>

	<div class="row">
		<div class="col-md-12">
		  <div class="actions form-group text-left">
		  	<%= link_to_add_topics "Agregar topic", lesson, :topics %>
		  </div>
	  </div>
	</div>
</fieldset>

<script>
// 	if ($('input.video_url').val() == "") {
// 		console.log("Video vacio");
// 	} else {
// 		console.log("Video lleno");
// 	}
</script>

app/views/courses/_resource_form.html.erb
<fieldset class="form-group register">
	<h3 class="right-line text-left">NUEVO RECURSO</h3>
	<div class="col-md-8 col-md-offset-4 text-left">
		<div class="field form-group">
			<%= resource.label :title, "Título:", class: "lead lead-lg" %>
			<%= resource.text_field :title, required: true, class: "form-control" %>
		</div>

		<div class="field form-group">
			<%= resource.label :description, "Descripción:", class: "lead lead-lg" %>
			<%= resource.text_area :description, required: true,class: "form-control" %>
		</div>

		<div class="field form-group">
			<%= resource.label :link_url, "URL del recurso:", class: "lead lead-lg" %>
			<%= resource.text_field :link_url, required: true, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= resource.hidden_field :_destroy %>
			<%= link_to "Borrar Recurso", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
		</div>
	</div>
</fieldset>

app/views/courses/_topic_form.html.erb
<fieldset class="form-group register">
	<h3 class="right-line text-left">NUEVO TOPIC</h3>
	<div class="col-md-10 col-md-offset-2 text-left">
		<div class="field form-group">
		<%= topic.label :title, "Título:", class: "lead lead-lg" %>
		<%= topic.text_field :title, required: true, class: "form-control" %>
		</div>

		<div class="field form-group">
		<%= topic.label :description, "Descripción:", class: "lead lead-lg" %>
		<%= topic.text_area :description, required: true,class: "form-control" %>
		</div>

		<!-- Conditional to add Video or PDF file for topic -->
		<div class="field form-group">
			
			<h4>Contenido de apoyo para la guía, escoja si lleva Archivo PDF o Video Clip</h4>
			<select class="form-control content_select">
				<option disabled selected> Seleccione una opción </option>
			  <option value="pdf">Archivo PDF</option>
			  <option value="video">Video Clip desde Vimeo</option>						  
			</select>

			<div class="field form-group  pdf_field" style='display: none'>
			  <%= topic.label :document, "PDF de la guía:", class: "lead lead-lg" %>
			  <%= topic.file_field :document, class: "form-control file_input" %>
			</div>

			<div class="field form-group  video_field" style='display: none'>
				<%= topic.label :content_url, "URL Video:", class: "lead lead-lg" %>
				<%= topic.text_field :content_url, class: "form-control video_url" %>
			</div>
		</div>

		<div class="field form-group">
			<%= topic.label :activities, "Acciones para aplicar en proyecto:", class: "lead lead-lg" %>
			<p>Para almacenar las diferentes acciones que corresponden a este topic se debe hacer uso del siguiente formato, este contiene una lista no ordena con tags de HTML donde cada item debe ir entre tagas li, como se muestra a continuación:<br>
				&nbsp&nbsp&nbsp &ltul class="list-group"&gt<br>
					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &ltli class="list-group-item"&gtNombre de la acción&lt/li&gt<br>
				&nbsp&nbsp&nbsp &lt/ul&gt					
			</p>
			<%= topic.text_area :activities, required: true,:rows => 5, class: "form-control" %>
		</div>

		<div class="field form-group">
			<%= topic.label :transcription, "Videotexto(Transcription):", class: "lead lead-lg" %>
			<p>Para almacenar el texto en diferentes parrafos, debe hacer uso del siguiente formato, este contiene cada parrafo entre tags de HTML tipo p, como se muestra a continuación:<br><br>
				&ltp&gtLorem ipsum dolor sit amet, quo illud eleifend ne. Vel ei zril laudem quaestio, eu alia modus scriptorem vix. Qui ex pericula assentior, utamur ornatus patrioque an pro, ne equidem facilis phaedrum sea. Modo nullam nominati cu nam, cum ut choro quando nominavi. Has illud tation consulatu et. Cu antiopam tractatos ius, et hinc paulo vis.&lt/p&gt<br>
			</p>
			<%= topic.text_area :transcription, rows: 10, required: true,class: "form-control" %>
		</div>

		<div class="form-group">
		<%= topic.hidden_field :_destroy %>
		<%= link_to "Borrar Topic", "#", class: "remove_field btn btn-ar btn-lg btn-danger" %>
		</div>
	</div>							
</fieldset>

<div class="row">
	<div class="col-md-12">
	  <div class="actions form-group text-center">
	  	<%= link_to_add_resources "Click aqui para agregar un recurso", topic, :resources %>
	  </div>
  </div>
</div>

app/views/courses/edit.html.erb
<div class="container" id="course_container">
	<h2 class="right-line">EDITAR LA GUíA: <span class="green_color_text"><%= @course.title.upcase %></span></h2>
	<%= render 'form_edit' %>		
</div>

app/views/courses/index.html.erb
<div class="container-fluid">
	<div class="row">
		<h2 class="right-line">LISTADO DE GUÍAS EN LA PLATAFORMA</h2>
		<div class="col-md-12">
			<table class="table">
				<tr class="success">
					<th class="text-center lead lead-lg">No Guía</th>
					<th class="text-center lead lead-lg">Imagen</th>
					<th class="text-center lead lead-lg">Título</th>
					<th class="text-center lead lead-lg">Tipo</th>
					<th class="text-center lead lead-lg">Opciones</th>
				</tr>		
				<% @courses.each_with_index do |course,index| %>							
					<tr class="text-center">
						<td class="lead lead-sm vert-align text-center"><%= index+1 %></td>
						<% if course.image.url == "http://i592.photobucket.com/albums/tt5/Mardini03/765-default-avatar.png" %>
							<td class="vert-align text-center"><%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/765-default-avatar.png", class: "user-thumbnail" %></td>
						<% else %>
							<td class="lead lead-sm vert-align text-center"><%= image_tag course.image.url(:thumb) %></td>						
						<% end %>						
						<td class="lead lead-sm vert-align text-center"><%= course.title %></td>
						<td class="lead lead-sm vert-align text-center"><%= course.course_type.humanize %></td>						
						<td class="lead lead-sm vert-align text-center" style="width: 15%">
							<%= link_to '<i class="fa fa-eye text-center"></i>'.html_safe, course, class: "btn btn-ar btn-info", title: "Ver Guía" %>
							<%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_course_path(course), class: "btn btn-ar btn-warning", title: "Editar Guía" %>
							<%= link_to course_path(course.id), method: :delete, title: "Eliminar Guía", data: { confirm: '¿Esta seguro que desea eliminar la guía?' }, class: "btn btn btn-ar btn-danger" do %><i class="fa fa-trash"></i><% end %>
						</td>												
					</tr>								
				<% end %>
			</table>	
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 text-center col-md-offset-3" id="btn-new-user">
			<%= link_to "Crear Una Nueva Guía", new_course_path, class: "btn btn-lg btn-ar btn-success" %>
		</div>
	</div>
</div>

app/views/courses/my_courses.html.erb
<div class="container">
  <section class="margin-bottom" id="user-courses">
    <div class="row">
      <div class="col-md-12">
          <h2 class="right-line">MIS CURSOS</h2>
      </div>

      <% @courses.each do |course| %>
        <div class="col-sm-3 col-md-4">
          <div class="thumbnail">
            <img src="<%= course.image.url(:medium) %>" alt="..." class="thumbnail_custom_image">
            <div class="caption">
              <h3 class="course_title"><%= course.title %></h3>
              <p class="text-justify" id="course_description"><%= course.description %></p>                              
            </div>
            <div class="row course-caption">
              <% if user_signed_in? %>                  
                <% if current_user.courses.include?(course) %>
                  <div class="col-sm-3">
                    <%= link_to 'Ir al curso', course, class: "btn btn-ar btn-primary" %>
                  </div>
                  <div class="col-md-8 col-md-offset-1 col-sm-9 text-right">
                    <%= image_tag(course.instructors.first.image.url(:thumb), class: "instructor-image") %>
                    <%= course.instructors.first.name %>
                  </div>
                <% else %>
                  <div class="col-sm-3">
                  <%= link_to 'Ver Curso', course_information_path(:course_id => course.id), class: "btn btn-ar btn-warning" %>
                </div>
                <div class="col-md-8 col-md-offset-1 col-sm-9 text-right">
                  <%= image_tag(course.instructors.first.image.url(:thumb), class: "instructor-image") %>
                  <%= course.instructors.first.name %>
                </div>
                <% end %>
              <% else %>
                <div class="col-sm-3">
                  <%= link_to 'Ver curso', course_information_path(:course_id => course.id), class: "btn btn-ar btn-warning" %>
                </div>
                <div class="col-md-8 col-md-offset-1 col-sm-9 text-right">
                  <%= image_tag(course.instructors.first.image.url(:thumb), class: "instructor-image") %>
                  <%= course.instructors.first.name %>
                </div>                 
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

    </div> <!-- row -->
  </section>
</div>

app/views/courses/new.html.erb
<div class="container" id="course_container">
	<h2 class="right-line">CREAR UNA NUEVA GUÍA</h2>
	<%= render 'form_new' %>		
</div>