config/routes.rb
Rails.application.routes.draw do
  # Block route for devise registration controller
  devise_for :users
  root 'pages#home'
  resources :user, :controller => "user" do
    collection { post :import }
  end
  resources :courses
  resources :topics
  resources :instructors
  resources :categories
  resources :subscriptions, only: [:new, :create, :edit, :update]
  get 'mark_as_done' => 'topic_completition#mark_as_done'
  get 'course_information' => 'pages#course_information'
  get 'plans_information' => 'pages#plans_information'
  get 'politicas_servicio' => 'pages#politicas_servicio'
  get 'faq' => 'pages#faq'
  get 'my_courses' => 'courses#my_courses'
  get 'welcome_new_user' => 'pages#welcome_video_user'
  get 'welcome_new_subscriptor' => 'pages#welcome_video_subscriptor'
  get 'discourse/sso' => 'discourse_sso#sso'
  get 'search_by_category' => 'pages#search_by_category'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
	has_and_belongs_to_many :courses
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authenticate_user!
	before_filter :content_permission

	def index
		@categories = Category.all
	end

	def new	
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
  	  flash[:notice] = "La categoria #{@category.name} fue creada con exito"
  	  redirect_to categories_path
  	else
  		flash[:alert] = "Ha ocurrido un error y la categoria #{@category.name}, no ha sido almacenado"
    	render :action => 'new'
  	end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to categories_path
		else
			flash[:alert] = 'Se ha encontrado un error al intentar editar esta categoría'
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end
	private
		def category_params
  		params.require(:category).permit(:name)
		end
		
		def content_permission
	    unless current_user.admin? || current_user.content_manager?
	      redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos de administrador para acceder a esta ruta."
	    end
  	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, :html => { :id => "categoryForm"}) do |category| %>
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-left">
			<div class="field form-group">
				<%= category.label :name, "Nombre de la Categoría:", class: "lead lead-lg" %>
				<%= category.text_field :name, required: true, class: "form-control" %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="actions form-group text-center">		  	
  			<%= category.submit "Guardar Categoría", class: "btn btn-ar btn-lg btn-success" %>
  		</div>
		</div>	
	</div>

<% end %>

app/views/categories/edit.html.erb
<div class="container">
	<div class="row">
		<h2 class="right-line">EDITAR UNA CATEGORÍA</h2>
	</div>
	<%= render 'form' %>		
</div>

app/views/categories/index.html.erb
<div class="container">
	<div class="row">
		<h2 class="right-line">LISTADO DE USUARIOS REGISTRADOS</h2>
		<div class="col-md-8 col-md-offset-2">
			<table class="table">
				<tr>
					<th class="text-center lead lead-lg">No Categoría</th>
					<th class="text-center lead lead-lg">Nombre</th>
					<th class="text-center lead lead-lg">Opciones</th>
				</tr>
				<% @categories.each_with_index do |category,index| %>
					<tr class="text-center">
						<td class="lead lead-sm vert-align text-center"><%= index+1 %></td>						
						<td class="lead lead-sm vert-align text-center"><%= category.name %></td>
						<td class="lead lead-sm vert-align text-center"><%= link_to "Editar", edit_category_path(category), class: "btn btn-ar btn-warning" %>  <%= link_to category_path(category), method: :delete, data: { confirm: '¿Esta seguro que desea elminar esta usuario?' }, class: "btn btn-ar btn-danger" do %><span>Eliminar</span><% end %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 text-center col-md-offset-3" id="btn-new-user">
			<%= link_to "Crear Una Nueva Categoría", new_category_path, class: "btn btn-lg btn-ar btn-success" %>
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<div class="container">
	<div class="row">
		<h2 class="right-line">ALMACENAR UNA NUEVA CATEGORIA</h2>
	</div>
	<%= render 'form' %>		
</div>