config/routes.rb
Rails.application.routes.draw do
  # Block route for devise registration controller
  devise_for :users
  root 'pages#home'
  resources :user, :controller => "user" do
    collection { post :import }
  end
  resources :courses
  resources :topics
  resources :instructors
  resources :categories
  resources :subscriptions, only: [:new, :create, :edit, :update]
  get 'mark_as_done' => 'topic_completition#mark_as_done'
  get 'course_information' => 'pages#course_information'
  get 'plans_information' => 'pages#plans_information'
  get 'politicas_servicio' => 'pages#politicas_servicio'
  get 'faq' => 'pages#faq'
  get 'my_courses' => 'courses#my_courses'
  get 'welcome_new_user' => 'pages#welcome_video_user'
  get 'welcome_new_subscriptor' => 'pages#welcome_video_subscriptor'
  get 'discourse/sso' => 'discourse_sso#sso'
  get 'search_by_category' => 'pages#search_by_category'
end

app/views/layouts/_footer.html.erb
<aside id="footer-widgets">
  <div class="container">
    <div class="row">
			<div class="footer-widget">
        <h3 class="footer-widget-title">Guías Recientes</h3>
				<% @footer_courses.each do |course| %>
					<div class="col-md-4">
	          <div class="media">
							<% if user_signed_in? %>
							  <% if course.free? %>
							    <%#= link_to image_tag(course.image.url(:thumb)), course, class: "pull-left footer-thumb-mask" %>
    	            <div class="media-body">
                  	<h4 class="media-heading"><%= link_to course.title, course %></h4>
                  	<!-- <small><%= course.created_at.strftime("%d %b. %Y") %></small> -->
                	</div>
							  <% else %>
							  	<%#= link_to image_tag(course.image.url(:thumb)), course_information_path(:course_id => course.id), class: "pull-left footer-thumb-mask" %>
  		            <div class="media-body">
  	              	<h4 class="media-heading"><%= link_to course.title, course_information_path(:course_id => course.id) %></h4>
  	              	<!-- <small><%= course.created_at.strftime("%d %b. %Y") %></small> -->
  	            	</div>
							  <% end %>
							<% else %>
							  <%#= link_to image_tag(course.image.url(:thumb)), course_information_path(:course_id => course.id), class: "pull-left footer-thumb-mask" %>
  	            <div class="media-body">
                	<h4 class="media-heading"><%= link_to course.title, course_information_path(:course_id => course.id) %></h4>
                	<!-- <small><%= course.created_at.strftime("%d %b. %Y") %></small> -->
              	</div>
							<% end %>
          	</div>
        	</div>
				<% end %>
			</div>
    </div> <!-- row -->
  </div> <!-- container -->
</aside> <!-- footer-widgets -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <p> &copy; 2015 Business Hackers All rights reserved | <%= link_to 'Políticas de servicio', politicas_servicio_path, target: "all_blank", style:'color:white'%> | help@businesshackers.how
        | Developed By <a style="color: #ccc;text-decoration:underline;" target="_blank" href="http://kaizendevs.co">KaizenDevs</a></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav_bar.html.erb
<script>
	 mixpanel.track_links("#CrearCuentaGratisTop", "Crear Cuenta Gratis Top clicked");
</script>

<nav class="navbar navbar-static-top navbar-default navbar-inverse" role="navigation" id="header">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      	<span class="sr-only">Toggle navigation</span>
        <i class="fa fa-bars"></i>
      </button>
      <%= link_to 'Business<span>Hackers</span>'.html_safe, root_path, class: "navbar-brand" %>
    </div> <!-- navbar-header -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">   
      	<!-- <li><%#= link_to 'Buscar Guía', search_by_category_path %></li>
				<% if user_signed_in? %> -->
					<!-- <li><%#= link_to 'HacksBlog', root_path(anchor: 'user-courses') %></li> -->
					<li class="dropdown">
				    <a href="javascript:void(0);" class="dropdown-toggle no-modal" data-toggle="dropdown">Guías</a>
				     <ul class="dropdown-menu dropdown-menu-left">
							<li><%= link_to 'Todos las Guías', search_by_category_path %></li>
							<% if current_user.subscription.nil? %>
								<li><%= link_to 'Cuenta VIP', new_subscription_path, class: "no-modal" %></li>
							<% else %>		
								<li><%= link_to 'Editar Tarjeta de Crédito', edit_subscription_path(current_user.subscription.id), class: "no-modal" %></li>
							<% end %>
				    </ul>
					</li> 							         
				<% end %>           
        <% if user_signed_in? && current_user.admin? %>
        	<li><%= link_to 'Comunidad', "http://community.businesshackers.how", :target => '_blank' %></li>
					<li class="dropdown">
				    <a href="javascript:void(0);" class="dropdown-toggle no-modal" data-toggle="dropdown">Opciones Administrador</a>
				     <ul class="dropdown-menu dropdown-menu-left">
			        <li><%= link_to 'Usuarios Registrados', user_index_path, class: "no-modal" %></li>
			        <li role="separator" class="divider"></li>
			        <li><%= link_to 'Crear Guías', new_course_path, class: "no-modal" %></li>
			        <li><%= link_to 'Guías Publicadas', courses_path, class: "no-modal" %></li>
			        <li role="separator" class="divider"></li>
			        <li><%= link_to 'Crear Instructores', new_instructor_path, class: "no-modal" %></li>
			        <li><%= link_to 'Instructores Registrados', instructors_path, class: "no-modal" %></li>
			        <li role="separator" class="divider"></li>
			        <li><%= link_to 'Crear Categoría', new_category_path, class: "no-modal" %></li>
			        <li><%= link_to 'Categorías Almacenadas', categories_path, class: "no-modal" %></li>
				    </ul>
					</li> 
        	<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "no-modal" %></li>
        <% elsif user_signed_in? && current_user.content_manager? %>
        	<li><%= link_to 'Comunidad', "http://community.businesshackers.how", :target => '_blank', class: "no-modal" %></li>
					<li class="dropdown">
				    <a href="javascript:void(0);" class="dropdown-toggle no-modal" data-toggle="dropdown">Gestión de Guías</a>
				     <ul class="dropdown-menu dropdown-menu-left">
			        <li><%= link_to 'Crear Guías', new_course_path, class: "no-modal" %></li>
			        <li><%= link_to 'Guías Publicadas', courses_path, class: "no-modal" %></li>
				    </ul>
					</li>
					<li class="dropdown">
				    <a href="javascript:void(0);" class="dropdown-toggle no-modal" data-toggle="dropdown">Gestión de Instructores</a>
				     <ul class="dropdown-menu dropdown-menu-left">
			        <li><%= link_to 'Crear Instructores', new_instructor_path, class: "no-modal" %></li>
			        <li><%= link_to 'Instructores Registrados', instructors_path, class: "no-modal" %></li>
				    </ul>
					</li> 
					<li class="dropdown">
				    <a href="javascript:void(0);" class="dropdown-toggle no-modal" data-toggle="dropdown">Categorías</a>
				     <ul class="dropdown-menu dropdown-menu-left">
			        <li><%= link_to 'Crear Categoría', new_category_path, class: "no-modal" %></li>
			        <li><%= link_to 'Categorías Almacenadas', categories_path, class: "no-modal" %></li>
				    </ul>
					</li>  
        	<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "no-modal" %></li>
        <% elsif user_signed_in? && ( current_user.user? || current_user.vip_user? || current_user.guest? ) %>
        	<% if current_user.vip_user? || current_user.guest? %>					
						<li><%= link_to 'Comunidad', "http://community.businesshackers.how", :target => '_blank', class: "no-modal" %></li>	
					<% end %>						
					<li class="dropdown">
						<a href="javascript:void(0);" class="dropdown-toggle no-modal" data-toggle="dropdown" style="padding: 6px 30px 5px 15px;">
						<img alt="" class="thumb userMenu-thumb" height="40" src="<%= current_user.image.url(:thumb) %>"></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Editar Perfil', edit_user_path(current_user), class: "no-modal" %></li>
							<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: "no-modal" %></li>   
						</ul>
					</li>								         
			  <% else %>
			  	<!-- <li><%#= link_to 'HacksBlog', root_path(anchor: 'user-courses') %></li> -->
			  	<li><%= link_to 'FAQ', faq_path %></li>
			  	<li><%= link_to 'Guías', search_by_category_path %></li>
			  	<li><%= link_to 'Iniciar Sesión', new_user_session_path, class: "no-modal" %></li> 
			  	<li><%= link_to 'Crea Una Cuenta Gratis', new_user_registration_path, id:"CrearCuentaGratisTop", class: "btn btn-primary", style:"color:white"%></li> 
			  <% end %>                        
      </ul>
    </div><!-- navbar-collapse -->
  </div><!-- container -->
</nav>

app/views/layouts/_sign_in_modal.html.erb
<div class="modal fade" id="sign_in_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title text-center">Antes de que te vayas....</h2>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 vcenter" id="teacher_image_box">
            <%= image_tag( @course.instructors.first.image.url, class: "img-teacher img-responsive center-block" ) %>
          </div>
          <h4 class="text-center" style="color: #666;">Comienza a aprender las estrategias de empresarios y expertos exitosos creando tu cuenta gratis</h4>
          <div class="text-center">
            <%= link_to "Crear una cuenta gratis", new_user_registration_path, class: "btn btn-ar call-to-action no-modal btn-lg" %>
          </div>
        </div>
      </div>
      <div class="modal-footer text-center" style="text-align: center;!important">
        <a href="#" id="sign_in_modal_url" class="no-modal text-center">No gracias, no quiero crear negocios exitosos</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_subscription_modal.html.erb
<div class="modal fade" id="subscription_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title text-center">Antes de que te vayas....</h2>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 vcenter" id="teacher_image_box">
            <%= image_tag( @course.instructors.first.image.url, class: "img-teacher img-responsive center-block" ) %>
          </div>
          <h4 class="text-center" style="color: #666;">Comienza a aprender las estrategias de empresarios y expertos exitosos creando tu cuenta</h4>
          <div class="text-center">
            <%= link_to "Suscríbete a una Cuenta VIP desde $28.49/mes", new_subscription_path, class: "btn btn-ar call-to-action no-modal btn-lg" %>
          </div>
        </div>
      </div>
      <div class="modal-footer text-center" style="text-align: center;!important">
        <a href="#" id="subscription_modal_url" class="no-modal text-center">No gracias, no quiero crear negocios exitosos</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessHackers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
	  $(function(){
	  	Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
	  });
  </script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <!-- start Mixpanel -->
	<script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("8ef57c23dc2c015ca516fa8bb6ac70d2");
	</script><!-- end Mixpanel -->

</head>
<body>

<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-566CKS"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-566CKS');</script>
<!-- End Google Tag Manager -->
	
	<%= render 'layouts/nav_bar' %>

	<% if flash[:alert] %>
	  <div class="container-fluid">
	    <div class="row">
	      <div class="alert alert-danger text-center" role="alert"><%=flash[:alert]%></div>
	    </div>
	  </div>
	<%end%>
	<% if flash[:notice] %>
	  <div class="container-fluid">
	    <div class="row">
	      <div class="alert alert-success text-center" role="alert"><%=flash[:notice]%></div>
	    </div>
	  </div>
	<%end%>
	<%= yield %>

	<% if current_page?(root_path) || current_page?(course_information_path) %>
		<%= render 'layouts/footer' %>
	<% end %>

	</div> <!-- boxed -->
	</div> <!-- sb-site -->
</body>
</html>

app/views/layouts/blank_for_payments.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessBites</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
	  $(function(){
	  	Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
	  });
  </script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- start Mixpanel -->
	<script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("8ef57c23dc2c015ca516fa8bb6ac70d2");
	</script><!-- end Mixpanel -->
	
</head>
<body>

<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-566CKS"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-566CKS');</script>
<!-- End Google Tag Manager -->

	<% if flash[:alert] %>
	  <div class="container-fluid">
	    <div class="row">
	      <div class="alert alert-danger text-center" role="alert"><%=flash[:alert]%></div>
	    </div>
	  </div>
	<%end%>
	<% if flash[:notice] %>
	  <div class="container-fluid">
	    <div class="row">
	      <div class="alert alert-success text-center" role="alert"><%=flash[:notice]%></div>
	    </div>
	  </div>
	<%end%>
	<%= yield %>

	<% if current_page?(root_path) || current_page?(course_information_path) %>
		<%= render 'layouts/footer' %>
	<% end %>

	</div> <!-- boxed -->
	</div> <!-- sb-site -->
</body>
</html>